import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <Suspense>
            <Header />
            <main>{children}</main>
          </Suspense>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
